# Site settings
title: Vadym Ivanchuk
email: vadym.ivanchuk@gmail.com
description: Ventures of a Biomedical Engineer
baseurl: ""
url: "http://ivadym.github.io"
twitter_username: VadymIvanchuk
github_username: ivadym

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
