# Site settings
title: Vadym Ivanchuk
email: vadym.ivanchuk@gmail.com
description: Vadym Ivanchuk's Portfolio
url: http://ivadym.github.io

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
